# Generated by Django 5.1.4 on 2026-05-13 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TanzaniaRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_sw', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_mainland', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_sw', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='locations.tanzaniaregion')),
            ],
            options={
                'ordering': ['name_en'],
                'unique_together': {('region', 'slug')},
            },
        ),
    ]
