# Generated by Django 5.1.4 on 2026-05-13 14:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_sw', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Job Categories',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('title_sw', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('description', models.TextField()),
                ('description_sw', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('requirements_sw', models.TextField(blank=True)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('CASUAL', 'Casual / Daily'), ('INTERNSHIP', 'Internship'), ('VOLUNTEER', 'Volunteer')], default='FULL_TIME', max_length=20)),
                ('experience_level', models.CharField(choices=[('NO_EXPERIENCE', 'No Experience Required'), ('JUNIOR', 'Junior (0–2 years)'), ('MID', 'Mid-Level (2–5 years)'), ('SENIOR', 'Senior (5+ years)'), ('EXECUTIVE', 'Executive')], default='NO_EXPERIENCE', max_length=20)),
                ('education_level', models.CharField(choices=[('NONE', 'No Formal Education'), ('PRIMARY', 'Primary School'), ('O_LEVEL', 'Ordinary Level (Form 4)'), ('A_LEVEL', 'Advanced Level (Form 6)'), ('CERTIFICATE', 'Certificate'), ('DIPLOMA', 'Diploma'), ('DEGREE', "Bachelor's Degree"), ('MASTERS', "Master's Degree"), ('PHD', 'PhD')], default='NONE', max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('salary_display', models.CharField(blank=True, max_length=100)),
                ('cv_required', models.BooleanField(default=False)),
                ('application_method', models.CharField(choices=[('IN_APP', 'Apply via Search App'), ('WHATSAPP', 'Apply via WhatsApp'), ('EMAIL', 'Apply via Email'), ('WALK_IN', 'Walk-In')], default='IN_APP', max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_address', models.CharField(blank=True, max_length=255)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('positions_available', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='locations.district')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='locations.tanzaniaregion')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.jobcategory')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='jobs_job_status_57b86b_idx'), models.Index(fields=['region', 'category', 'status'], name='jobs_job_region__c22f07_idx'), models.Index(fields=['company'], name='jobs_job_company_9ee5ea_idx')],
            },
        ),
    ]
